version: "3"
services:

    # NOTE: do not change any of the services names 

    haproxy:
        image: haproxy
        ports: 
            - "80:80"
        container_name: 'clicknbuy_cnbhaproxy'
        volumes:
            - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
        networks: 
            main:
                ipv4_address: 172.18.0.2

    cnbapp1:
        build: .
        restart: "on-failure"
        environment: 
            - SPRING_DATASOURCE_URL=jdbc:mysql://cnbdb:3306/clickandbuyDB
            - SPRING_DATASOURCE_USERNAME=userDB
            - SPRING_DATASOURCE_PASSWORD=password
        ports: 
            - "8443:8443"
        expose:
            - "8443"
        networks:
            main:
                ipv4_address: 172.18.0.3
        depends_on: 
            - cnbdb
            - haproxy
    
    cnbapp2:
        build: .
        restart: "on-failure"
        environment: 
            - SPRING_DATASOURCE_URL=jdbc:mysql://cnbdb:3306/clickandbuyDB
            - SPRING_DATASOURCE_USERNAME=userDB
            - SPRING_DATASOURCE_PASSWORD=password
        ports: 
            - "8444:8443"
        expose:
            - "8444"
        networks:
            main:
                ipv4_address: 172.18.0.5
        depends_on: 
            - cnbdb
            - haproxy

    cnbdb:
        image: mysql:latest
        restart: "on-failure"
        environment: 
            - MYSQL_ROOT_PASSWORD=admi1234
            - MYSQL_USER=userDB
            - MYSQL_PASSWORD=password
            - MYSQL_DATABASE=clickandbuyDB
        ports: 
            - "8084:3306"
        expose: 
            - "3306"
        networks: 
            main:
                ipv4_address: 172.18.0.3
        volumes: 
            - ./cnbdbvol:/var/lib/mysql

    cnbinternal:
        build: ./internal-service
        restart: "on-failure"
        ports: 
            - "8081:8081"
        networks:
            main:
                ipv4_address: 172.18.0.4

networks:
    main:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.2/16

volumes: 
    cnbdbvol: