version: '2'
services:
    mysql-clicknbuy:
        restart: on-failure
        container_name: mysql-clicknbuy
        image: mysql:8.0
        environment: 
            MYSQL_DATABASE: clickandbuyDB
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: userDB
            MYSQL_PASSWORD: password
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
        ports:
            - "6033:3306"
        healthcheck:
            # test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""
            test: "echo db healthcheck"
            interval: 2s
            timeout: 20s
            retries: 3

    clicknbuyapp:
        restart: on-failure
        build: ./
        expose:
            - "8443"
        ports:
            - "8443:8443"
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-clicknbuy:6033/clickandbuyDB?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
            - SPRING_DATASOURCE_USERNAME=userDB
            - SPRING_DATASOURCE_PASSWORD=password
        links:
            - mysql-clicknbuy