version: "3"
services:

    # NOTE: do not change any of the services names

    # When docker-compose up this file access the webpage 
    # through the balancer located at 172.18.0.2:443

    haproxy:
        image: haproxy
        ports: 
            - "80:80"
        container_name: 'clicknbuy_cnbhaproxy'
        volumes:
            - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
            - ./haproxy/key.pem:/usr/local/etc/ssl/key.pem:ro
        networks: 
            main:
                ipv4_address: 172.18.0.2
        depends_on: 
            - cnbapp1
            - cnbapp2

    cnbapp1:
        build: .
        container_name: 'cnbapp1'
        restart: "on-failure"
        environment: 
            - SPRING_DATASOURCE_URL=jdbc:mysql://cnbdb:3306/clickandbuyDB
            - SPRING_DATASOURCE_USERNAME=userDB
            - SPRING_DATASOURCE_PASSWORD=password
        ports: 
            - "8080:8080"
        expose:
            - "8080"
        networks:
            main:
                ipv4_address: 172.18.0.5
        depends_on: 
            - cnbdb
    
    cnbapp2:
        build: .
        container_name: 'cnbapp2'
        restart: "on-failure"
        environment: 
            - SPRING_DATASOURCE_URL=jdbc:mysql://cnbdb:3306/clickandbuyDB
            - SPRING_DATASOURCE_USERNAME=userDB
            - SPRING_DATASOURCE_PASSWORD=password
        ports: 
            - "8082:8080"
        expose:
            - "8082"
        networks:
            main:
                ipv4_address: 172.18.0.6
        depends_on: 
            - cnbdb

    cnbdb:
        image: mysql:latest
        restart: "on-failure"
        environment: 
            - MYSQL_ROOT_PASSWORD=admi1234
            - MYSQL_USER=userDB
            - MYSQL_PASSWORD=password
            - MYSQL_DATABASE=clickandbuyDB
        ports: 
            - "8084:3306"
        expose: 
            - "3306"
        networks: 
            main:
                ipv4_address: 172.18.0.3
        volumes: 
            - ./cnbdbvol:/var/lib/mysql

    cnbinternal:
        build: ./internal-service
        restart: "on-failure"
        ports: 
            - "8081:8081"
        networks:
            main:
                ipv4_address: 172.18.0.4

networks:
    main:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.2/16

volumes: 
    cnbdbvol: