version: '2'
services:
    mysql-clicknbuy:
        restart: on-failure
        container_name: mysql-clicknbuy
        image: mysql:8.0
        environment: 
            MYSQL_DATABASE: clickandbuyDB
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: userDB
            MYSQL_PASSWORD: password
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
        ports:
            - "6033:3306"
        healthcheck:
            test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""
            interval: 2s
            timeout: 20s
            retries: 10

    clicknbuyapp:
        restart: on-failure
        build: ./
        expose:
            - "8443"
        ports:
            - 8443:8443
        environment:
            WAIT_HOSTS: mysql:3306
        depends_on:
            - mysql-clicknbuy