version: "3"
services:
    cnbapp:
        build: .
        restart: "on-failure"
        environment: 
            - SPRING_DATASOURCE_URL=jdbc:mysql://cnbdb:3306/clickandbuyDB
            - SPRING_DATASOURCE_USERNAME=userDB
            - SPRING_DATASOURCE_PASSWORD=password
        ports: 
            - "8443:8443"
        networks:
            - main
        depends_on: 
            - cnbdb

    cnbdb:
        image: mysql:latest
        restart: "on-failure"
        environment: 
            - MYSQL_ROOT_PASSWORD=admi1234
            - MYSQL_USER=userDB
            - MYSQL_PASSWORD=password
            - MYSQL_DATABASE=clickandbuyDB
        ports: 
            - "8084:3306"
        expose: 
            - "3306"
        networks: 
            - main
        volumes: 
            - cnbdbvol:/var/lib/mysql

networks:
    main:

volumes: 
    cnbdbvol: