version: "3"

services:

  database:
    image: mysql:latest
    ports:
      - "3307:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=clickandbuy
    restart: always
    
    
  web:
    build: .
    ports:
      - "8443:8443"
    links:
     - database
    environment:
     - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/clickandbuy
    restart: always

